/**
 * Вопросы и короткие ответы Ольги — содержимое страницы /faq.
 *
 * ТЕКСТЫ ЕЁ, ДОСЛОВНО. Перенесены из `QUESTIONS.md` в корне репозитория
 * (документ «Olganomics 50 Questions and Answers»), там же отмечено, что она
 * проверила и что опубликовано. Правятся только вместе с ней — принципы 2 и 3
 * в CONTEXT.md. Наше здесь — только порядок и названия разделов.
 *
 * ВСЁ НА ОДНОЙ СТРАНИЦЕ. Пятьдесят ответов сначала были разложены по пяти
 * страницам, по курсам. Мы их собрали обратно, и вот почему. Человек,
 * зашедший в FAQ, должен видеть ответы, а не карточки «читать дальше».
 * Домен новый, веса у него нет, и одна страница, на которую ведут все
 * ссылки, соберёт его быстрее, чем пять страниц по шестьсот слов; Google
 * сам умеет открывать длинную страницу на нужном абзаце. Разделить обратно
 * будет уместно, когда у темы наберётся несколько полных статей — тогда у
 * неё появится собственный раздел, а ответ здесь будет вести в него.
 *
 * ПОРЯДОК РАЗДЕЛОВ. Сначала уроки и консультация: за этим на FAQ приходят
 * чаще всего, и это последний шаг перед разговором. Дальше AP®, потом IGCSE.
 *
 * `id` вопроса — якорь в адресе (/faq#scarce-mean-rare-economics). По нему
 * ссылаются на конкретный ответ; их же показывают поисковики и нейросети,
 * когда цитируют кусок страницы. После публикации якоря не меняются —
 * иначе чужие ссылки перестанут попадать в ответ.
 *
 * `n` — номер вопроса в документе Ольги. По нему сверяют, что опубликовано.
 */

export interface Answer {
  /** Номер вопроса в документе Ольги (QUESTIONS.md). */
  n: number;
  /** Якорь в адресе. После публикации не меняется. */
  id: string;
  q: string;
  a: string;
}

export interface AnswerSection {
  /** Якорь раздела — для указателей наверху страницы. */
  id: string;
  title: string;
  items: Answer[];
}

export const ANSWER_SECTIONS: AnswerSection[] = [
  {
    id: 'lessons',
    title: 'Lessons and the free consultation',
    items: [
      { n: 46, id: 'economics-lessons-like', q: 'What are Economics lessons with you like?', a: 'I want you to understand what\'s happening economically and be able to explain it yourself. We look at where you\'re getting stuck, work through the idea and practise applying it. That might involve a graph, a multiple-choice question or a written answer. I\'ll explain why an answer works and help you see what to change when it doesn\'t.' },
      { n: 47, id: 'online-economics-lessons-work', q: 'How do your online Economics lessons work?', a: 'We meet in a live online session and work through explanations and questions together. You\'ll need to take part, write answers and draw graphs, just as you would in a classroom. I use your reasoning to see where you need help. Before we start, we\'ll agree the lesson arrangements and what materials you\'ll need.' },
      { n: 48, id: 'take-lessons-if-dont-live-jordan', q: 'Can I take lessons with you if I don\'t live in Jordan?', a: 'Yes, you can contact me about online lessons from outside Jordan. Tell me your country, time zone, subject, exam board and exam date. We can then check whether there\'s a suitable lesson time and format for you. Individual lessons, groups and live sessions have different scheduling options, so we\'ll discuss what fits.' },
      { n: 49, id: 'happens-first-economics-consultation', q: 'What happens in my first Economics consultation with you?', a: 'We\'ll talk about your course, what you\'re finding difficult and what you want help with. If you have recent work or diagnostic results, those can make the conversation more useful. The aim is to identify a sensible next step, whether that\'s focused practice or a suitable lesson option. You can also ask me about how the lessons work.' },
      { n: 50, id: 'choose-individual-lessons-group-lessons-or', q: 'Should I choose individual lessons, group lessons or a live session for my child?', a: 'I\'d start with where your child needs help. Individual lessons give us room to focus on their particular gaps and pace. A group can work well when the level and schedule suit them. A live session is useful for a specific topic or practice focus. Tell me what your child is struggling with, and we can discuss which option makes sense.' },
    ],
  },
  {
    id: 'ap-course',
    title: 'AP® Economics: the course, the exam and tutoring',
    items: [
      { n: 1, id: 'ap-economics-hard', q: 'Is AP Economics hard?', a: 'It can feel difficult at first, especially when you have to choose a graph or work out why an answer is wrong. But you don\'t need to memorise every possible question. My advice is to understand the economic logic, then practise applying it. When you can explain why something happens, unfamiliar questions become much more manageable.' },
      { n: 2, id: 'which-harder-ap-micro-or-ap', q: 'Which is harder: AP Micro or AP Macro?', a: 'It depends on how you think. Micro looks at consumers, businesses and individual markets. Macro looks at the whole economy, including inflation, unemployment and economic policy. You might enjoy Micro\'s business examples but find its firm diagrams challenging, or prefer Macro\'s bigger picture. I wouldn\'t choose based only on which one someone else calls easier.' },
      { n: 3, id: 'start-studying-ap-economics-exam', q: 'When should I start studying for my AP Economics exam?', a: 'Start while you\'re learning the topics. After a lesson, try a few questions and draw the relevant graph yourself. That tells you whether the idea has really made sense. I wouldn\'t leave all your exam practice until the final weeks. If you\'ve started late, begin with what you know now and identify the gaps you need to work on first.' },
      { n: 4, id: 'many-hours-week-study-ap-economics', q: 'How many hours a week should I study for AP Economics?', a: 'There isn\'t a magic number. I\'d start with a few focused study sessions each week and see what you can actually do afterwards. Can you answer questions without notes? Can you explain a graph? If you\'re taking both Micro and Macro, allow time for each. Your progress should guide your schedule; simply spending longer at your desk doesn\'t show what you\'ve learned.' },
      { n: 5, id: 'get-5-ap-economics-without-tutor', q: 'Can I get a 5 in AP Economics without a tutor?', a: 'Yes, you can. If you understand the course, practise consistently and can check your work properly, independent study may be enough. A tutor can help when you keep getting stuck or can\'t see why you\'re losing marks. I would look at the support you need before recommending lessons. A 5 is a goal to work towards, never something anyone should guarantee.' },
      { n: 6, id: 'know-if-child-falling-behind-ap', q: 'How do I know if my child is falling behind in AP Economics?', a: 'Look beyond one disappointing grade. Is your child missing work, repeating the same mistakes or spending hours studying without being able to answer questions independently? Ask them to explain a recent topic in their own words. I\'d also speak with their teacher. Together, their work and feedback can show whether there\'s a particular gap that needs attention.' },
      { n: 7, id: 'child-need-ap-economics-tutor', q: 'Does my child need an AP Economics tutor?', a: 'Possibly, but I\'d first want to understand what\'s going wrong. Does your child struggle with the concepts, the graphs or explaining answers under time pressure? Sometimes a few focused lessons are enough. Sometimes regular support makes more sense. If they\'re progressing well on their own, extra tutoring may not be necessary. The starting point should be their actual needs.' },
      { n: 8, id: 'choose-good-ap-economics-tutor', q: 'How do I choose a good AP Economics tutor?', a: 'Look for someone who can explain clearly and show your child why an answer earns or loses marks. Ask how they teach graphs, work through exam questions and respond when a student doesn\'t understand. I\'d also ask how they check progress. You should come away with a clear idea of how the lessons will help your child.' },
      { n: 9, id: 'one-one-or-group-ap-economics', q: 'Are one-to-one or group AP Economics lessons better?', a: 'Both can work well. One-to-one lessons give us more freedom to slow down and focus on your particular difficulties. In a group, you can discuss ideas and learn from questions other students ask. I\'d choose according to your current understanding and the group\'s pace. If you\'re missing several foundations, individual support may be the better place to begin.' },
      { n: 10, id: 'ive-started-ap-economics-late-catch', q: 'I\'ve started AP Economics late. How can I catch up?', a: 'First, let\'s find out what you\'ve missed and what you already understand. Start with the foundations that your current lessons depend on, then practise questions straight away. You don\'t need to finish reading the whole textbook before doing any practice. Make a realistic weekly plan, keep up with new work and return to the mistakes that haven\'t quite clicked yet.' },
    ],
  },
  {
    id: 'ap-strategy',
    title: 'AP® exam strategy: practice and mistakes',
    items: [
      { n: 11, id: 'get-5-ap-microeconomics', q: 'How can I get a 5 in AP Microeconomics?', a: 'Start by checking what you can do without help. Can you explain a market change, draw a firm\'s graph and work through a calculation? Practise across the whole course using both multiple-choice questions and free-response questions. Then spend time understanding your mistakes. I\'d focus especially on the questions where you\'re unsure what to do, even if practising familiar ones feels more comfortable.' },
      { n: 12, id: 'get-5-ap-macroeconomics', q: 'How can I get a 5 in AP Macroeconomics?', a: 'Work on connecting the steps in your explanation. If spending changes, what happens next, and why? Which model shows it? Would the result be different in the long run? Practise those connections alongside calculations, graphs and exam questions. My advice is to explain your reasoning aloud: if you can\'t explain a step, that\'s a useful place to focus your revision.' },
      { n: 13, id: 'whats-best-way-practise-ap-economics', q: 'What\'s the best way to practise AP Economics multiple-choice questions?', a: 'Do a small set properly. Answer without notes, then check why the correct option works and why the others don\'t. Include the questions you guessed correctly; those can hide a gap too. I\'d rather you understand ten questions fully than rush through fifty and only count your score. Once your reasoning is secure, start working on your speed.' },
      { n: 14, id: 'choose-between-two-answers-ap-economics', q: 'How do I choose between two answers in AP Economics MCQs?', a: 'Go back to the exact question. What has changed? What are you being asked to find? Two options can sound reasonable, but one may rely on an assumption the question never gives you. Compare the difference between the options carefully. If you\'re still unsure, write out the economic reasoning instead of choosing the answer with the most familiar words.' },
      { n: 15, id: 'mistakes-avoid-ap-economics-frqs', q: 'What mistakes should I avoid in AP Economics FRQs?', a: 'Make sure you answer every part and follow the instruction: identifying an outcome is different from explaining it. Label your graphs carefully and show calculations when asked. Before moving on, check that your graph and written explanation tell the same story. A useful final question is: have I actually shown what this part asked me to show?' },
      { n: 16, id: 'why-understand-economics-class-but-lose', q: 'Why do I understand Economics in class but lose marks on tests?', a: 'In class, the explanation helps you follow the steps. In a test, you have to decide which steps to take yourself. You may understand the topic but still hesitate over the graph, the wording or how much to explain. Try unfamiliar questions without notes. Then look closely at where you got stuck; that tells you what to practise next.' },
      { n: 17, id: 'ive-done-ap-economics-practice-test', q: 'I\'ve done an AP Economics practice test. How should I review my mistakes?', a: 'Don\'t stop at checking the answer letter. Ask yourself why you missed it: did you misunderstand the concept, overlook a word or make a calculation error? Write a short explanation of the correct reasoning. Then try a similar question and come back to it a few days later. You want to recognise the idea again, not just remember that the answer was C.' },
      { n: 18, id: 'often-timed-ap-economics-practice', q: 'How often should I do timed AP Economics practice?', a: 'Start with short timed sets once you can work through the questions accurately without a timer. You could try one each week and adjust as the exam gets closer. Later, practise longer sections so you can manage your time across different questions. Always leave time to review. Another timed test won\'t fix a misunderstanding you haven\'t looked at yet.' },
      { n: 19, id: 'ai-help-me-study-ap-economics', q: 'Can AI help me study AP Economics?', a: 'Yes, AI can help you review a concept, ask for a simpler explanation or generate another example. But be careful with exam questions. AI can mix up very similar MCQ options and confidently choose the wrong answer. It also cannot always read an Economics graph accurately or give reliable feedback on your labels, shifts and equilibrium points. Use AI to support your learning, but ask your teacher or tutor to check difficult MCQs and graphs.' },
      { n: 20, id: 'ap-economics-exam-month-focus', q: 'My AP Economics exam is in a month. What should I focus on?', a: 'Start with your recent mistakes. Which topics still make you hesitate? Work on those, then use mixed timed practice to check whether you can apply what you\'ve reviewed. Keep drawing graphs and writing explanations yourself. I\'d make a manageable weekly plan with time to correct your work and rest, rather than trying to cover everything again at the same depth.' },
    ],
  },
  {
    id: 'ap-concepts',
    title: 'AP® Microeconomics: concepts and graphs',
    items: [
      { n: 21, id: 'scarce-mean-rare-economics', q: 'Does scarce mean rare in Economics?', a: 'No. Rare means unusual or difficult to find. Scarce means limited compared with what people want. Bread is not rare because it is available in many shops, but it is still scarce: producing it requires limited flour, labour, ovens and time. In Economics, almost all goods and resources are scarce because using them involves a choice and an opportunity cost.' },
      { n: 22, id: 'whats-difference-between-scarcity-shortage', q: 'What\'s the difference between scarcity and a shortage?', a: 'Scarcity is the permanent economic problem that resources are limited while human wants are unlimited. A shortage happens in a particular market when quantity demanded is greater than quantity supplied at the current price. For example, imagine a bakery sells bread for a very low price. Customers want 100 loaves, but the bakery supplies only 60. There is a shortage of 40 loaves. The price may adjust and remove the shortage, but scarcity still exists because flour, labour and time remain limited.' },
      { n: 23, id: 'demand-curve-shift-move-along-it', q: 'When does the demand curve shift, and when do I move along it?', a: 'First ask what changed. If the product\'s own price changes, there is a movement along the same demand curve. For example, if the price of coffee falls from 3 JDs to 2 JDs and people buy more coffee, move down along the existing demand curve. If a factor other than coffee\'s own price changes, the whole demand curve shifts. If consumers\' incomes rise and coffee is a normal good, demand shifts right because people want more coffee at every price. If coffee becomes less popular, demand shifts left because people want less coffee at every price.' },
      { n: 24, id: 'supply-curve-shift-move-along-it', q: 'When does the supply curve shift, and when do I move along it?', a: 'Again, start with what changed. If the product\'s own price changes, there is a movement along the same supply curve. For example, if the price of bread rises, bakeries may supply more bread, so move up along the existing supply curve. If a production factor changes, the whole supply curve shifts. If flour becomes cheaper, production costs fall and supply shifts right because bakeries can offer more bread at every price. If electricity becomes more expensive, production costs rise and supply shifts left because bakeries offer less bread at every price.' },
      { n: 25, id: 'know-which-economics-graph-draw', q: 'How do I know which Economics graph to draw?', a: 'Don\'t touch your pencil yet. First ask what is happening economically. Then identify the market and the variables in the question. For example, if the question says consumers\' incomes rise and they buy more restaurant meals, draw the market for restaurant meals with price on the vertical axis and quantity on the horizontal axis. Because income is a demand shifter, shift demand to the right. If the question is about unemployment, inflation or the price level for the whole economy, you may need a macroeconomic model instead of a market demand and supply graph.' },
      { n: 26, id: 'one-word-really-change-economics-graph', q: 'Can one word really change my Economics graph?', a: 'Yes. One word can describe a completely different economic change. If the price of coffee falls, quantity demanded increases and you move along the same demand curve. If consumers\' preference for coffee increases, demand increases and the whole curve shifts right. The words price and preference lead to different graph changes. Read the full situation, identify what changed and only then decide whether you need a movement or a shift.' },
      { n: 27, id: 'calculate-opportunity-cost', q: 'How do I calculate opportunity cost?', a: 'Opportunity cost is what you give up to get one more unit of something. Use this simple rule: amount given up divided by amount gained. For example, if a country can produce either 10 cars or 20 computers, producing 1 car costs 2 computers: 20 computers divided by 10 cars equals 2 computers per car. Producing 1 computer costs 0.5 car: 10 cars divided by 20 computers equals 0.5 car per computer. Always write the units so your answer is clear.' },
      { n: 28, id: 'work-out-who-has-comparative-advantage', q: 'How do I work out who has comparative advantage?', a: 'Comparative advantage always belongs to the producer with the lower opportunity cost. First identify whether the question gives output or input data. For an output question, calculate the opportunity cost of product A as output of B divided by output of A. For example, if Country X can produce 20 phones or 10 tablets, the opportunity cost of 1 tablet is 20 phones divided by 10 tablets, or 2 phones. For an input question using time, labour or raw materials, calculate the opportunity cost of A as input needed for A divided by input needed for B. For example, if one table takes 4 hours and one chair takes 2 hours, the opportunity cost of 1 table is 4 divided by 2, or 2 chairs. Calculate the same product for each producer and compare the answers. Whoever has the lowest opportunity cost has comparative advantage in that product.' },
      { n: 29, id: 'know-if-ppc-shifts-or-theres', q: 'How do I know if the PPC shifts or there\'s a movement along it?', a: 'Ask whether productive capacity has changed. If an economy reallocates its existing resources from wheat to cars, move from point A to point B along the same PPC: more cars means less wheat. If the economy gets more workers or better technology that improves production of both goods, the whole PPC shifts outward. If a recession leaves workers and factories unemployed, production can move from a point on the PPC to a point inside it; the curve itself does not shift because the economy still has the same productive capacity.' },
      { n: 30, id: 'label-ap-economics-graph', q: 'How should I label an AP Economics graph?', a: 'Start with a clear title, such as Market for Coffee or Production Possibilities Curve. Label both axes with the correct variables. In a market graph, the vertical axis is Price and the horizontal axis is Quantity. On a PPC, each axis shows the output of one good, such as Cars and Wheat. Label every curve: D and S for demand and supply, or PPC for the production possibilities curve. If a curve shifts, keep the original label and give the new curve a second label, such as D1 to D2 or S1 to S2. If there is movement along a curve, mark the original and new positions as points A and B and use an arrow when helpful. A graph should never look like an unlabeled stick: every line, curve, axis and important point must tell the examiner what it represents.' },
    ],
  },
  {
    id: 'igcse-economics',
    title: 'IGCSE Economics',
    items: [
      { n: 31, id: 'start-revising-igcse-economics', q: 'When should I start revising for IGCSE Economics?', a: 'Begin as you learn each topic. You don\'t need to wait until you\'ve finished the syllabus to practise questions. Review the idea, explain it in your own words and try applying it. Graphs and written reasoning improve with regular practice. Use the syllabus for your exam board and exam year to keep track of what you still need to cover.' },
      { n: 32, id: 'igcse-economics-difficult', q: 'Is IGCSE Economics difficult?', a: 'It can be challenging when you move from learning definitions to explaining unfamiliar situations. You might know what a term means but struggle to use it in an answer. That\'s a skill you can develop. I\'d start with simple examples, build the explanation step by step and practise questions that make you use the idea yourself.' },
      { n: 33, id: 'whats-best-way-revise-igcse-economics', q: 'What\'s the best way to revise for IGCSE Economics?', a: 'Choose a topic and check what you remember before opening your notes. Then answer questions that make you use it, including diagrams and calculations where relevant. Check your answers and work out what needs improving. I\'d keep returning to earlier topics too. Being able to recognise a page in your textbook isn\'t the same as being able to explain the economics.' },
      { n: 34, id: 'know-definitions-why-am-still-losing', q: 'I know the definitions. Why am I still losing marks in IGCSE Economics?', a: 'Definitions are a starting point. The question may ask you to explain an effect, use information or discuss an argument. Knowing what inflation means, for example, doesn\'t automatically explain how it affects a household whose income stays the same. After learning a definition, ask yourself: can I use this idea to explain a real situation?' },
      { n: 35, id: 'write-better-analysis-igcse-economics', q: 'How do I write better analysis in IGCSE Economics?', a: 'Explain the links in your reasoning. For example, if production costs rise, firms may supply less at each price. With demand unchanged, equilibrium price rises and quantity falls. Each step should follow from the one before it. When you check your answer, ask whether you\'ve explained why the outcome happens or simply named the outcome.' },
      { n: 36, id: 'good-evaluation-look-like-igcse-economics', q: 'What does good evaluation look like in IGCSE Economics?', a: 'When you\'re asked to discuss or make a judgement, think about what could change your answer. Would the effect depend on how large the change is, how much time passes or who is affected? Explain that connection. Writing \'it depends\' by itself doesn\'t tell the examiner much. Make sure the depth of your answer fits your exam board and the question.' },
      { n: 37, id: 'need-draw-diagram-igcse-economics-answer', q: 'Do I need to draw a diagram in my IGCSE Economics answer?', a: 'Draw one if the question asks for it. Otherwise, use a diagram when it helps you explain your point and suits the task. Label it clearly and refer to the change in your writing. Don\'t assume the examiner will supply the explanation for you. If the question asks you to explain, show how your diagram supports that explanation.' },
      { n: 38, id: 'mistakes-avoid-igcse-economics', q: 'What mistakes should I avoid in IGCSE Economics?', a: 'Read the instruction carefully before you write. A definition won\'t fully answer an \'explain\' question, and a list of effects may need more development. Use any relevant data or context provided, and check your diagrams. I\'d also look back at the question at the end: did you answer what it actually asked, or just write what you know about the topic?' },
    ],
  },
  {
    id: 'igcse-business',
    title: 'IGCSE Business',
    items: [
      { n: 39, id: 'child-start-preparing-igcse-business', q: 'When should my child start preparing for IGCSE Business?', a: 'I\'d start building exam skills during the course, rather than leaving them until revision season. Your child needs time to practise applying ideas to different businesses and explaining decisions. Short, regular practice gives them a chance to use feedback and improve. Make sure the materials match their exam board and exam year, especially when choosing past papers.' },
      { n: 40, id: 'understand-igcse-business-why-arent-marks', q: 'I understand IGCSE Business. Why aren\'t my marks higher?', a: 'You may know the theory but need more practice showing how it applies to the business in the question. For example, naming a source of finance is only a first step. Can you explain why it suits that business and what the consequences would be? I\'d look at your written answers to see whether the missing piece is application, analysis or judgement.' },
      { n: 41, id: 'use-case-study-igcse-business-answer', q: 'How do I use the case study in my IGCSE Business answer?', a: 'Choose a detail that matters to your argument and explain why. If a small bakery has limited cash, show how a large loan repayment could put pressure on its finances. Simply repeating the bakery\'s name doesn\'t make the answer specific. Ask yourself: would this point change if I were writing about a different business?' },
      { n: 42, id: 'whats-difference-between-analysis-evaluation-igcse', q: 'What\'s the difference between analysis and evaluation in IGCSE Business?', a: 'Analysis explains what could happen and why. Staff training, for example, might reduce mistakes and cut waste costs. Evaluation takes that reasoning further: are those benefits worth the training cost for this particular business? You need to weigh what matters and support your judgement. A conclusion is stronger when you explain why you\'ve chosen it.' },
      { n: 43, id: 'write-good-long-answer-igcse-business', q: 'How do I write a good long answer in IGCSE Business?', a: 'Pause and plan before writing. Choose relevant points, connect them to the business and explain their consequences. If the question asks for a judgement, justify it using the most important factors in this case. You don\'t need to fill the page with everything you know. Follow the question, its marks and your exam board\'s expectations.' },
      { n: 44, id: 'mistakes-cost-marks-igcse-business', q: 'What mistakes cost marks in IGCSE Business?', a: 'An answer can sound sensible but still be too general. Watch for copied case details that you haven\'t explained, advantages you\'ve only listed and conclusions without reasons. Keep bringing your answer back to the business. Why does this point matter here? What would it mean for its costs, customers or objectives? Develop the points that actually answer the question.' },
      { n: 45, id: 'revise-igcse-business-without-copying-out', q: 'How can I revise IGCSE Business without copying out the whole textbook?', a: 'Turn a topic into a few questions and try answering from memory. Then use the ideas in a short case or an exam question. Check whether you\'ve applied and explained them properly. Keep brief notes on what you missed. I\'d spend more time improving an answer than making pages of notes that you never test yourself on.' },
    ],
  },
];

/** Все вопросы подряд — для разметки FAQPage и проверок. */
export const ALL_ANSWERS: Answer[] = ANSWER_SECTIONS.flatMap((s) => s.items);
